### PR TITLE
Revert "build: add source-map-support for better stack traces"

### PR DESCRIPTION
**Pull request by nolanmar511**
Reverts GoogleCloudPlatform/cloud-profiler-nodejs#60

### CODE REVIEW

**Comment by aalexand** [comment]
LGTM, it's not super clear why there are 4 commits in this PR though.

**Comment by ofrobots** [comment]
That is super confusing indeed. @nolanmar511 did you revert by clicking 'revert' from #60? There's only one commit on that PR.

**Comment by ofrobots** [comment]
Looking at the commit history in git, the history does look clean because squash-and-merge was used, but the commit message is still extremely confusing. Perhaps the confusion comes from package-lock.json which might have had conflicting changes (@nolanmar511 did you have to resolve?)

I am going to force-push re-write of the commit log to clean things up.

**Comment by nolanmar511** [comment]
There were no conflicts which had to be resolved. 
And I did confirm that no unexpected changes were made after merging.

**Pull request merged**
