### PR TITLE
chore: add test for starting and running agent.

### PR DESCRIPTION
**Pull request by nolanmar511**

### CODE REVIEW

**Comment by aalexand** [comment]
Is there a reason you updated against the master using the merge and not the rebase? Seeing these merge commits in a pull request is super weird.

**Comment by nolanmar511** [comment]
Fixed commit history.

**Comment by ofrobots** [comment]
An end to end test should talk to the real profiler service rather than a mocked service. Is there a reason why this wasn't done?

**Comment by aalexand** [comment]
@ofrobots That non-hermetic test should be a separate one.

**Comment by aalexand** [comment]
Anything holding this?

**Pull request merged**
