### PR TITLE
build: add error_details definitions

### PR DESCRIPTION
**Pull request by ofrobots**
~~DO NOT LAND YET~~

Add js & type definitions generated from error_details.proto.

Fixes: https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/issues/77

### CODE REVIEW

**Comment by aalexand** [comment]
This doesn't fix #77 alone, right? I expect we should also start using it. Or am I commenting against unfinished work? Apologies if so.

**Comment by ofrobots** [comment]
Well, since #75 hasn't landed yet, we could either consider this to 'fix' #77, and adjust #75, or wait for #75 to land and address the issue here.

I would be okay with either.

**Comment by aalexand** [comment]
Ah, OK. I'm fine with either too.

**Comment by aalexand** [comment]
@nolanmar511 As discussed, take these changes and make the definitions actually used, as a separate PR. This one will be closed then.

**Comment by ofrobots** [comment]
I would like to close this PR at this point. It would be fairly easy to get back the definitions, and the issue #77 remains open to track the work needed.

If this is a mistake, go ahead and reopen.

**Pull request closed without merging**
