### PR TITLE
Add profile.proto and third party directory

### PR DESCRIPTION
**Pull request by matthewloring**
Proto imported from https://github.com/google/pprof

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL.

**Comment by ofrobots** [comment]
Since the file doesn't contain a copyright, can you include the LICENSE file from the upstream project into the `third_party/proto` directory. Also include a README.google file documenting the upstream location this file was copied from.

/cc @rauls5382

**Comment by matthewloring** [comment]
@ofrobots PTAL.

**Comment by ofrobots** [comment]
Lgtm

**Pull request merged**
