### PR TITLE
chore: release 0.1.11

### PR DESCRIPTION
**Pull request by nolanmar511**
Release notes: https://github.com/GoogleCloudPlatform/cloud-profiler-nodejs/releases/edit/untagged-b424fc0140ffadf35280

### CODE REVIEW

**Comment by jinwoo** [comment]
Did you mean to change `package.json`? I see only `package-lock.json`.

**Comment by jinwoo** [comment]
And can you also create a draft release note for this release? After this PR is checked in, you can publish the release note, which will also create a version tag, which in turn will publish a new NPM.

**Comment by nolanmar511** [comment]
Ack -- updated so package.json is modified.

**Comment by jinwoo** [comment]
No draft release note? I'm fine if you want to create one after this is checked in. But our guideline suggests you create a draft release note before checking in a PR that bumps up the version (like this). The idea is that the reviewer can review the release note as well and agree on the versioning decision (e.g. semver major/minor/patch) by looking at what are the changes for the release.

**Comment by nolanmar511** [comment]
Just created draft release notes.

**Comment by aalexand** [comment]
@nolanmar511 I don't see the release note draft in this PR?

**Comment by jinwoo** [comment]
I'd expect some information in the release note :) At least a list of commits since the last release.

You can get the commit list by
```shell
$ git log --pretty=oneline v0.1.10..HEAD
```

**Comment by aalexand** [comment]
The description of the PR say "Supports Node >=8.9.4 and >=6.12.3." but I believe these versions were supported by the previous 0.1.9 release as well?

**Comment by aalexand** [comment]
Here is an [example](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/commit/49725182944cebfdc855be4e9953e9db29a0cd72) of what Cloud Trace agent release notes look like.

Not sure and curious why the commit to update the version in package.json is [separate](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/commit/19b1bd426d69186c098737191ec654c8522dfdfc) and is not via a PR.

**Comment by jinwoo** [comment]
@aalexand Node team decided to use GitHub's release notes instead of separate ChangeLog or Release files in the repo.

**Comment by jinwoo** [comment]
E.g. release notes for js-green-licenses: https://github.com/google/js-green-licenses/releases

**Comment by nolanmar511** [comment]
Release notes now include commits since last release.

**Pull request merged**
