### PR TITLE
chore: add circle-ci config

### PR DESCRIPTION
**Pull request by nolanmar511**
This necessary for setting up automated release.

### CODE REVIEW

**Comment by jinwoo** [comment]
FYI. To make CircleCI build for PRs, you have to turn on "Build forked pull requests" in the Advanced Settings of the CircleCI project.

**Comment by nolanmar511** [comment]
I don't think I have access to the settings for this project since I am not an admin for this repo. So I don't think I can enable CircleCI builds.

**Comment by ofrobots** [comment]
Enabled CircleCI. Also enabled builds on PRs from forks. @nolanmar511, if you push a change here (just do `git commit --amend`, and then force push to your fork without changes), that should kick off the CircleCI.

**Comment by nolanmar511** [comment]
PTAL

**Pull request merged**
